logging:
  level:
    root: INFO

spring:
  application:
    name: ${SPRING_APPLICATION_NAME}

  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

info:
  app:
    name: ${SPRING_APPLICATION_NAME}
    description: "FYP Grading project - Registry Server"
    version: ${BUILD_VERSION}

# these properties are here instead of the config server because the latter is dependent on eureka
management:
  endpoints:
    web:
      exposure: # exposes /actuator endpoints over HTTP
        include: '*'
  info:
    env:
      enabled: true # includes environment-specific info in /actuator/info
  endpoint:
    health:
      probes:
        enabled: true
    shutdown:
      enabled: true # /actuator/shutdown to shut down gracefully (TO BE SECURED)
  health: # /actuator/health
    readinessstate: # /actuator/health/readiness
      enabled: true
    livenessstate: # /actuator/health/liveness
      enabled: true
  metrics:
    tags:
      application: ${SPRING_APPLICATION_NAME}

eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
  client:
    register-with-eureka: true
    fetch-registry: false
    healthcheck:
      enabled: true

server:
  port: ${PORT}
